import { z } from "zod";
import { officialUscUrl } from "../../contracts/src/review.js";

export const CLEARANCE_REGISTRY_VERSION = "2026-09-06.1";
export const VERIFIED_AT = "2026-09-06T23:08:51.000Z";
export const REVIEW_AFTER = "2026-10-06T23:08:51.000Z";
export const DIRECTORY_EVIDENCE =
  "https://academicprograms.usc.edu/wp-content/uploads/2025/08/AEA-Navigation-Guides-D-Clearance.pdf";
const entry = z
  .object({
    id: z.string(),
    title: z.string().max(160),
    url: officialUscUrl,
    audience: z.string().max(240),
    note: z.string().max(600),
    terms: z.array(z.number().int()).min(1),
    prefixes: z.array(z.string()).optional(),
    schools: z.array(z.string()).optional(),
    min_number: z.number().optional(),
    max_number: z.number().optional(),
  })
  .strict()
  .refine((e) => !!e.prefixes?.length || !!e.schools?.length);
export type ClearanceEntry = z.infer<typeof entry>;
// Editorial instructions, not rules declaring that a section requires or has clearance.
// Every entry is scoped to the researched term; use the official catalog for other terms.
export const clearanceRegistry = z.array(entry).parse([
  {
    id: "csci",
    title: "Computer Science D-clearance instructions",
    url: "https://www.cs.usc.edu/students/d-clearance/",
    prefixes: ["CSCI", "DSCI"],
    terms: [20263],
    audience: "CSCI/DSCI students and students requesting their courses",
    note: "Choose the instructions for your degree level and program. Major, partner-program, on-campus and DEN procedures differ. Check current section flags; this page contains several registration periods.",
  },
  {
    id: "ee-preengineering",
    title: "EE pre-engineering registration guidance",
    url: "https://viterbiundergrad.usc.edu/pre-engineering/registration-d-clearance/",
    prefixes: ["EE"],
    max_number: 499,
    terms: [20263],
    audience: "Pre-engineering students seeking EE courses",
    note: "The EE guidance directs eligible pre-engineering students to the ECE department in myViterbi. Its intended-major conditions apply to this audience; other students should use the course department's instructions.",
  },
  {
    id: "viterbi-manager",
    title: "Viterbi D-clearance request system information",
    url: "https://viterbiit.usc.edu/services/information-services/d-clearance-request-manager/",
    prefixes: ["AME", "BME", "CE", "CSCI", "EE", "ISE"],
    terms: [20263],
    audience: "Students directed to myViterbi by these departments",
    note: "This describes the departmental request system, not current course eligibility or an open application window. Follow your department's current instructions.",
  },
  {
    id: "ise",
    title: "Industrial and Systems Engineering clearance guidance",
    url: "https://ise.usc.edu/current-students/",
    prefixes: ["ISE"],
    terms: [20263],
    audience: "ISE and non-ISE undergraduate, master's and doctoral students",
    note: "Undergraduate advising/email and graduate myViterbi procedures differ. DEN uses a separate route. The page also contains older term dates; confirm the current window with the department.",
  },
  {
    id: "tac",
    title: "Technology and Applied Computing registration instructions",
    url: "https://tac.usc.edu/advisement-original/registration-instructions/",
    prefixes: ["TAC", "ITP"],
    terms: [20263],
    audience: "Students requesting Technology and Applied Computing courses",
    note: "Use the advising contact and course-specific instructions on this page for clearance and prerequisite questions.",
  },
  {
    id: "sae",
    title: "Systems Architecting and Engineering student resources",
    url: "https://sae.usc.edu/graduate-student-resources/",
    prefixes: ["SAE"],
    terms: [20263],
    audience: "SAE graduate students",
    note: "The department links its clearance instructions here. Check the course's own department when requesting an outside elective.",
  },
  {
    id: "dornsife-undergrad",
    title: "Dornsife Fall 2026 course clearance directory",
    url: "https://dornsife.usc.edu/dash/d-clearance-info/",
    schools: ["DRNS"],
    max_number: 499,
    terms: [20263],
    audience: "Students seeking Dornsife undergraduate courses",
    note: "Find your exact course and section in the directory. Instructions vary by course and may require instructor approval or a departmental form. GE-office prefixes and CORE have separate instructions.",
  },
  {
    id: "dornsife-graduate",
    title: "Dornsife graduate clearance guidance",
    url: "https://dornsife.usc.edu/dash/d-clearance-info/",
    schools: ["DRNS"],
    min_number: 500,
    terms: [20263],
    audience: "Students seeking Dornsife graduate courses",
    note: "The directory's course tables cover undergraduate Fall 2026 offerings. For graduate-course clearance, it directs students to their master's or doctoral program advisor.",
  },
  {
    id: "ge-office",
    title: "GE office registration and clearance guidance",
    url: "https://dornsife.usc.edu/ge/registration/",
    prefixes: ["GESM", "FESM", "MDA", "INDS"],
    terms: [20263],
    audience: "Students seeking courses administered by the GE office",
    note: "Use the relevant course instructions and registration window. A GE category such as GE-D is not itself a D-clearance requirement.",
  },
  {
    id: "hbio",
    title: "Human Biology student advisement and clearance",
    url: "https://dornsife.usc.edu/heb/student-advisement/",
    prefixes: ["HBIO"],
    terms: [20263],
    audience:
      "Human Biology students seeking advising and upper-division clearance",
    note: "The department links a clearance form and describes required advising. This is not evidence that a particular student has been approved.",
  },
  {
    id: "physics",
    title: "Physics undergraduate clearance instructions",
    url: "https://dornsife.usc.edu/physics/undergraduate-office/",
    prefixes: ["PHYS", "ASTR"],
    max_number: 499,
    terms: [20263],
    audience: "Students seeking Physics and Astronomy undergraduate clearance",
    note: "Use the department's linked clearance form or undergraduate office contact.",
  },
  {
    id: "cinema",
    title: "Cinematic Arts departmental clearance contacts",
    url: "https://cinema.usc.edu/degrees/minor/dclearanceContacts.cfm",
    prefixes: ["CNTV", "CTAN", "CTCS", "CTIN", "CTPR", "CTWR", "IML"],
    terms: [20263],
    audience:
      "Students seeking SCA courses; contact depends on the course prefix and level",
    note: "Choose the contact for the course prefix, not your minor name. Some departments distinguish undergraduate and graduate requests.",
  },
  {
    id: "cinema-majors",
    title: "Cinematic Arts major clearance procedures",
    url: "https://cinema.usc.edu/studentaffairs/dclearance.cfm",
    schools: ["CNMA"],
    terms: [20263],
    audience: "Cinematic Arts majors",
    note: "The school directs majors to their academic advisor through Advise USC. Follow the department-specific process for your course.",
  },
  {
    id: "animation",
    title: "CTAN Fall 2026 elective registration update",
    url: "https://cinema.usc.edu/studentaffairs/animation.cfm",
    prefixes: ["CTAN"],
    terms: [20263],
    audience: "Students seeking CTAN electives",
    note: "The page reports a change from D to R for Fall electives. If the cached section still indicates D, confirm its current WebReg flag; do not assume clearance or other permissions have been granted.",
  },
  {
    id: "roski",
    title: "Roski Fall 2026 D-clearance instructions",
    url: "https://roski.usc.edu/d-clearance-for-fall-2026/",
    schools: ["FINE"],
    terms: [20263],
    audience: "Roski majors, minors, graduate students and non-Roski students",
    note: "Choose your student group and the current registration period. Earlier webforms and clearances have expiration dates; the page also gives later email and add/drop procedures.",
  },
  {
    id: "price-ug",
    title: "Price undergraduate D-clearance requests",
    url: "https://priceschool.usc.edu/students/registration-d-clearance/undergraduate/",
    schools: ["PPDP"],
    max_number: 499,
    terms: [20263],
    audience: "Students requesting undergraduate Price courses",
    note: "The Fall 2026 list links PPD 240, PPD 245 and PPD/RED 301 requests. Use the linked academic advisor directory when your course is not listed.",
  },
  {
    id: "price-grad",
    title: "Price graduate D-clearance requests",
    url: "https://priceschool.usc.edu/students/registration-d-clearance/graduate/",
    schools: ["PPDP"],
    min_number: 500,
    terms: [20263],
    audience: "Students requesting graduate Price courses",
    note: "Choose your program and follow its current instructions; different programs use different request routes.",
  },
  {
    id: "marshall-ug",
    title: "Marshall undergraduate registration and clearance",
    url: "https://students.marshall.usc.edu/current-students/academic-advising/forms-and-other-resources/registration-information-interest-lists",
    schools: ["BUS", "ACTN"],
    max_number: 499,
    terms: [20263],
    audience:
      "Students requesting undergraduate business or accounting courses",
    note: "Course-specific procedures and after-first-week instructor approval differ. Accounting links to separate instructions. A closed interest list is not an open clearance request.",
  },
  {
    id: "marshall-nonmajor",
    title: "Non-Marshall graduate course clearance guidance",
    url: "https://students.marshall.usc.edu/graduate-students/registration-information/non-marshall-graduate-student-resources/frequently-asked-questions",
    schools: ["BUS", "ACTN"],
    min_number: 500,
    max_number: 599,
    terms: [20263],
    audience: "Non-Marshall graduate students only",
    note: "Review the eligibility conditions and linked application. Marshall students should follow their own program's registration instructions.",
  },
  {
    id: "annenberg",
    title: "Annenberg academic forms and clearance instructions",
    url: "https://annenberg.usc.edu/current-students/academic-forms",
    schools: ["ANSC"],
    terms: [20263],
    audience: "Annenberg students and students seeking Annenberg courses",
    note: "Choose the relevant course, program and semester. Some clearance forms are distributed to majors/minors separately; non-major windows differ.",
  },
  {
    id: "thornton",
    title: "Thornton student affairs and clearance routes",
    url: "https://music.usc.edu/students/",
    schools: ["MUS"],
    terms: [20263],
    audience: "Thornton majors, minors and non-Thornton students",
    note: "Select the major, minor or individual-instruction route. Clearance procedures depend on the type of course and your student group.",
  },
  {
    id: "kaufman",
    title: "Kaufman student affairs D-clearance forms",
    url: "https://kaufman.usc.edu/student-affairs/",
    prefixes: ["DANC"],
    terms: [20263],
    audience: "Students seeking Dance courses",
    note: "The student affairs page links separate D-clearance and prerequisite-waiver forms. Directed research has an additional approval process.",
  },
  {
    id: "dramatic-arts",
    title: "Dramatic Arts student services clearance guidance",
    url: "https://dramaticarts.usc.edu/aso/",
    prefixes: ["THTR"],
    terms: [20263],
    audience: "Students seeking Dramatic Arts clearance",
    note: "The student services guidance points to the SDA student portal's D-Clearance Course Request. Confirm current access and instructions there.",
  },
  {
    id: "iovine-young",
    title: "Iovine and Young non-major course guidance",
    url: "https://iovine-young.usc.edu/learn/undergraduate/academy-non-major-course-offerings",
    schools: ["ACAD"],
    max_number: 499,
    terms: [20263],
    audience: "Non-Academy students seeking undergraduate Academy courses",
    note: "Check the published non-major course/section list and the advising contact. Academy majors should follow their own advising process.",
  },
  {
    id: "gerontology",
    title: "Gerontology D-clearance and registration FAQ",
    url: "https://gero.usc.edu/academics/academic-advisement/advisement-faqs/",
    prefixes: ["GERO"],
    terms: [20263],
    audience: "Students seeking Gerontology courses",
    note: "The FAQ links the clearance request form and explains the student advisor's role. Requesting clearance does not reserve a seat.",
  },
  {
    id: "social-work",
    title: "Social Work and Nursing registration guidance",
    url: "https://dworakpeck.usc.edu/student-life/enrollment-services/registration-information",
    schools: ["SWDP", "NURS"],
    terms: [20263],
    audience: "Dworak-Peck students and USC students seeking its courses",
    note: "Required-course clearance and additional/non-program course requests follow different procedures. Use Enrollment Services instructions appropriate to your program.",
  },
  {
    id: "chan",
    title: "Chan student services and departmental clearance",
    url: "https://chan.usc.edu/students/student-services",
    schools: ["OCST"],
    terms: [20263],
    audience: "Students seeking Chan Occupational Science/Therapy courses",
    note: "The Student Services team handles course registration and departmental clearance. Use the contact instructions for your program.",
  },
]);
